apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  annotations:
    kapp.k14s.io/identity: v1;/carto.run/ClusterSupplyChain/source-to-url;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"ClusterSupplyChain","metadata":{"labels":{"kapp.k14s.io/app":"1670868064772922211","kapp.k14s.io/association":"v1.4e1a1027543b1d663294132ebfdd4f33"},"name":"source-to-url"},"spec":{"params":[{"name":"maven_repository_url","value":"https://repo.maven.apache.org/maven2"},{"default":"main","name":"gitops_branch"},{"default":"supplychain","name":"gitops_user_name"},{"default":"supplychain","name":"gitops_user_email"},{"default":"supplychain@cluster.local","name":"gitops_commit_message"},{"default":"","name":"gitops_ssh_secret"}],"resources":[{"name":"source-provider","params":[{"name":"serviceAccount","value":"default"},{"name":"gitImplementation","value":"go-git"}],"templateRef":{"kind":"ClusterSourceTemplate","name":"source-template"}},{"name":"image-provider","params":[{"name":"serviceAccount","value":"default"},{"name":"registry","value":{"ca_cert_data":"","repository":"tap/supply-chain","server":"registry.source-lab.io"}},{"default":"default","name":"clusterBuilder"},{"default":"./Dockerfile","name":"dockerfile"},{"default":"./","name":"docker_build_context"},{"default":[],"name":"docker_build_extra_args"}],"sources":[{"name":"source","resource":"source-provider"}],"templateRef":{"kind":"ClusterImageTemplate","options":[{"name":"kpack-template","selector":{"matchFields":[{"key":"spec.params[?(@.name==\"dockerfile\")]","operator":"DoesNotExist"}]}},{"name":"kaniko-template","selector":{"matchFields":[{"key":"spec.params[?(@.name==\"dockerfile\")]","operator":"Exists"}]}}]}},{"images":[{"name":"image","resource":"image-provider"}],"name":"config-provider","params":[{"name":"serviceAccount","value":"default"}],"templateRef":{"kind":"ClusterConfigTemplate","name":"convention-template"}},{"configs":[{"name":"config","resource":"config-provider"}],"name":"app-config","templateRef":{"kind":"ClusterConfigTemplate","options":[{"name":"config-template","selector":{"matchLabels":{"apps.tanzu.vmware.com/workload-type":"web"}}},{"name":"server-template","selector":{"matchLabels":{"apps.tanzu.vmware.com/workload-type":"server"}}},{"name":"worker-template","selector":{"matchLabels":{"apps.tanzu.vmware.com/workload-type":"worker"}}}]}},{"configs":[{"name":"app_def","resource":"app-config"}],"name":"service-bindings","templateRef":{"kind":"ClusterConfigTemplate","name":"service-bindings"}},{"configs":[{"name":"app_def","resource":"service-bindings"}],"name":"api-descriptors","templateRef":{"kind":"ClusterConfigTemplate","name":"api-descriptors"}},{"configs":[{"name":"config","resource":"api-descriptors"}],"name":"config-writer","params":[{"name":"serviceAccount","value":"default"},{"name":"registry","value":{"ca_cert_data":"","repository":"tap/supply-chain","server":"registry.source-lab.io"}}],"templateRef":{"kind":"ClusterTemplate","name":"config-writer-template"}},{"name":"deliverable","params":[{"name":"registry","value":{"ca_cert_data":"","repository":"tap/supply-chain","server":"registry.source-lab.io"}}],"templateRef":{"kind":"ClusterTemplate","name":"deliverable-template"}}],"selectorMatchExpressions":[{"key":"apps.tanzu.vmware.com/workload-type","operator":"In","values":["web","server","worker"]}]}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
  creationTimestamp: "2022-12-12T18:01:04Z"
  generation: 1
  labels:
    kapp.k14s.io/app: "1670868064772922211"
    kapp.k14s.io/association: v1.4e1a1027543b1d663294132ebfdd4f33
  name: source-to-url
  resourceVersion: "1798504"
  uid: 4efb1231-f7da-4215-a114-f52ed251a965
spec:
  params:
  - name: maven_repository_url
    value: https://repo.maven.apache.org/maven2
  - default: main
    name: gitops_branch
  - default: supplychain
    name: gitops_user_name
  - default: supplychain
    name: gitops_user_email
  - default: supplychain@cluster.local
    name: gitops_commit_message
  - default: ""
    name: gitops_ssh_secret
  resources:
  - name: source-provider
    params:
    - name: serviceAccount
      value: default
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
  - name: image-provider
    params:
    - name: serviceAccount
      value: default
    - name: registry
      value:
        ca_cert_data: ""
        repository: tap/supply-chain
        server: registry.source-lab.io
    - default: default
      name: clusterBuilder
    - default: ./Dockerfile
      name: dockerfile
    - default: ./
      name: docker_build_context
    - default: []
      name: docker_build_extra_args
    sources:
    - name: source
      resource: source-provider
    templateRef:
      kind: ClusterImageTemplate
      options:
      - name: kpack-template
        selector:
          matchFields:
          - key: spec.params[?(@.name=="dockerfile")]
            operator: DoesNotExist
      - name: kaniko-template
        selector:
          matchFields:
          - key: spec.params[?(@.name=="dockerfile")]
            operator: Exists
  - images:
    - name: image
      resource: image-provider
    name: config-provider
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterConfigTemplate
      name: convention-template
  - configs:
    - name: config
      resource: config-provider
    name: app-config
    templateRef:
      kind: ClusterConfigTemplate
      options:
      - name: config-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: web
      - name: server-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: server
      - name: worker-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: worker
  - configs:
    - name: app_def
      resource: app-config
    name: service-bindings
    templateRef:
      kind: ClusterConfigTemplate
      name: service-bindings
  - configs:
    - name: app_def
      resource: service-bindings
    name: api-descriptors
    templateRef:
      kind: ClusterConfigTemplate
      name: api-descriptors
  - configs:
    - name: config
      resource: api-descriptors
    name: config-writer
    params:
    - name: serviceAccount
      value: default
    - name: registry
      value:
        ca_cert_data: ""
        repository: tap/supply-chain
        server: registry.source-lab.io
    templateRef:
      kind: ClusterTemplate
      name: config-writer-template
  - name: deliverable
    params:
    - name: registry
      value:
        ca_cert_data: ""
        repository: tap/supply-chain
        server: registry.source-lab.io
    templateRef:
      kind: ClusterTemplate
      name: deliverable-template
  selectorMatchExpressions:
  - key: apps.tanzu.vmware.com/workload-type
    operator: In
    values:
    - web
    - server
    - worker
status:
  conditions:
  - lastTransitionTime: "2022-12-12T18:01:04Z"
    message: ""
    reason: Ready
    status: "True"
    type: TemplatesReady
  - lastTransitionTime: "2022-12-12T18:01:04Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
  observedGeneration: 1
